pool:
  vmImage: ubuntu-latest

stages:
- stage: SAST
  jobs:
  - job: SAST
    displayName: 'SAST'
    steps:

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'token-lab-final'
    organization: 'lab-final-devsecops'
    scannerMode: 'MSBuild'
    projectKey: 'Lab-Final-DevSecOps_spring-boot-kubernetes'
    projectName: 'spring-boot-kubernetes'

- task: Maven@4
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false



- task: dependency-check-build-task@6
  inputs:
    projectName: 'test-dependecycheck'
    scanPath: '**/*.java'
    format: 'HTML'
